# Generated by Django 4.0.2 on 2022-02-06 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='Таймкод')),
                ('text', models.CharField(max_length=128, verbose_name='Текст песни')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Файл песни')),
                ('timecode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.timecode', verbose_name='Таймкод')),
            ],
        ),
    ]
