# Generated by Django 4.0.2 on 2022-02-07 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Файл песни')),
            ],
        ),
        migrations.CreateModel(
            name='Timecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.CharField(max_length=5, verbose_name='Начало таймкода')),
                ('finish_at', models.CharField(max_length=5, verbose_name='Конец таймкода')),
                ('text', models.CharField(max_length=128, verbose_name='Текст песни')),
                ('transcription', models.CharField(max_length=128, verbose_name='Транскрипция песни')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timecodes', to='player.song', verbose_name='Песня')),
            ],
        ),
    ]
