# Generated by Django 4.0.2 on 2022-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecode',
            name='text',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст песни'),
        ),
        migrations.AlterField(
            model_name='timecode',
            name='transcription',
            field=models.CharField(blank=True, max_length=128, verbose_name='Транскрипция песни'),
        ),
    ]
